name: Artemis
url: https://github.com/Dreyer/hexo-theme-artemis

menu:
  Home: /
  About: /about
  Quotes: /quotes
  Archives: /archives
  RSS: /atom.xml

favicon: /favicon.ico
logo: /sahil_dojo420.png

# Comment
# e.g disqus: seansun
disqus: sahil-cc

# Analytics
mathjax: false
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
